In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report

In [121]:
!pip install pandas_profiling

Collecting pandas_profiling
  Using cached pandas_profiling-2.8.0-py2.py3-none-any.whl (259 kB)
Requirement already satisfied: jinja2>=2.11.1 in c:\forpit2\lib\site-packages (from pandas_profiling) (2.11.1)
Collecting visions[type_image_path]==0.4.4
  Using cached visions-0.4.4-py3-none-any.whl (59 kB)
Collecting pandas!=1.0.0,!=1.0.1,!=1.0.2,>=0.25.3
  Using cached pandas-1.1.1-cp37-cp37m-win_amd64.whl (9.4 MB)
Requirement already satisfied: numpy>=1.16.0 in c:\forpit2\lib\site-packages (from pandas_profiling) (1.18.1)
Collecting matplotlib>=3.2.0
  Using cached matplotlib-3.3.1-1-cp37-cp37m-win_amd64.whl (8.9 MB)
Collecting tqdm>=4.43.0
  Using cached tqdm-4.48.2-py2.py3-none-any.whl (68 kB)
Collecting missingno>=0.4.2
  Using cached missingno-0.4.2-py3-none-any.whl (9.7 kB)
Requirement already satisfied: htmlmin>=0.1.12 in c:\forpit2\lib\site-packages (from pandas_profiling) (0.1.12)
Requirement already satisfied: scipy>=1.4.1 in c:\forpit2\lib\site-packages (from pandas_profiling) (1.4.1)
Collecting phik>=0.9.10
  Using cached phik-0.10.0-py3-none-any.whl (599 kB)
Requirement already satisfied: joblib in c:\forpit2\lib\site-packages (from pandas_profiling) (0.14.1)
Requirement already satisfied: astropy>=4.0 in c:\forpit2\lib\site-packages (from pandas_profiling) (4.0)
Collecting tangled-up-in-unicode>=0.0.6
  Using cached tangled_up_in_unicode-0.0.6-py3-none-any.whl (3.1 MB)
Collecting requests>=2.23.0
  Using cached requests-2.24.0-py2.py3-none-any.whl (61 kB)
Requirement already satisfied: confuse>=1.0.0 in c:\forpit2\lib\site-packages (from pandas_profiling) (1.3.0)
Requirement already satisfied: ipywidgets>=7.5.1 in c:\forpit2\lib\site-packages (from pandas_profiling) (7.5.1)
Requirement already satisfied: MarkupSafe>=0.23 in c:\forpit2\lib\site-packages (from jinja2>=2.11.1->pandas_profiling) (1.1.1)
Requirement already satisfied: networkx>=2.4 in c:\forpit2\lib\site-packages (from visions[type_image_path]==0.4.4->pandas_profiling) (2.4)
Requirement already satisfied: attrs>=19.3.0 in c:\forpit2\lib\site-packages (from visions[type_image_path]==0.4.4->pandas_profiling) (19.3.0)
Requirement already satisfied: Pillow; extra == "type_image_path" in c:\forpit2\lib\site-packages (from visions[type_image_path]==0.4.4->pandas_profiling) (7.0.0)
Processing c:\users\0737~1\appdata\local\pip\cache\wheels\16\72\b0\e5be34699908d9ff25dcb3debbb717987b766af61bbddffdfe\imagehash-4.1.0-py2.py3-none-any.whl
Requirement already satisfied: pytz>=2017.2 in c:\forpit2\lib\site-packages (from pandas!=1.0.0,!=1.0.1,!=1.0.2,>=0.25.3->pandas_profiling) (2019.3)
Requirement already satisfied: python-dateutil>=2.7.3 in c:\forpit2\lib\site-packages (from pandas!=1.0.0,!=1.0.1,!=1.0.2,>=0.25.3->pandas_profiling) (2.8.1)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\forpit2\lib\site-packages (from matplotlib>=3.2.0->pandas_profiling) (1.1.0)
Requirement already satisfied: cycler>=0.10 in c:\forpit2\lib\site-packages (from matplotlib>=3.2.0->pandas_profiling) (0.10.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 in c:\forpit2\lib\site-packages (from matplotlib>=3.2.0->pandas_profiling) (2.4.6)
Collecting certifi>=2020.06.20
  Downloading certifi-2020.6.20-py2.py3-none-any.whl (156 kB)
Requirement already satisfied: seaborn in c:\forpit2\lib\site-packages (from missingno>=0.4.2->pandas_profiling) (0.10.0)
Requirement already satisfied: numba>=0.38.1 in c:\forpit2\lib\site-packages (from phik>=0.9.10->pandas_profiling) (0.48.0)
Requirement already satisfied: idna<3,>=2.5 in c:\forpit2\lib\site-packages (from requests>=2.23.0->pandas_profiling) (2.8)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\forpit2\lib\site-packages (from requests>=2.23.0->pandas_profiling) (1.25.8)
Requirement already satisfied: chardet<4,>=3.0.2 in c:\forpit2\lib\site-packages (from requests>=2.23.0->pandas_profiling) (3.0.4)
Requirement already satisfied: pyyaml in c:\forpit2\lib\site-packages (from confuse>=1.0.0->pandas_profiling) (5.3)
Requirement already satisfied: widgetsnbextension~=3.5.0 in c:\forpit2\lib\site-packages (from ipywidgets>=7.5.1->pandas_profiling) (3.5.1)
Requirement already satisfied: ipykernel>=4.5.1 in c:\forpit2\lib\site-packages (from ipywidgets>=7.5.1->pandas_profiling) (5.1.4)
Requirement already satisfied: ipython>=4.0.0; python_version >= "3.3" in c:\forpit2\lib\site-packages (from ipywidgets>=7.5.1->pandas_profiling) (7.12.0)
Requirement already satisfied: traitlets>=4.3.1 in c:\forpit2\lib\site-packages (from ipywidgets>=7.5.1->pandas_profiling) (4.3.3)
Requirement already satisfied: nbformat>=4.2.0 in c:\forpit2\lib\site-packages (from ipywidgets>=7.5.1->pandas_profiling) (5.0.4)
Requirement already satisfied: decorator>=4.3.0 in c:\forpit2\lib\site-packages (from networkx>=2.4->visions[type_image_path]==0.4.4->pandas_profiling) (4.4.1)
Requirement already satisfied: PyWavelets in c:\forpit2\lib\site-packages (from imagehash; extra == "type_image_path"->visions[type_image_path]==0.4.4->pandas_profiling) (1.1.1)
Requirement already satisfied: six in c:\forpit2\lib\site-packages (from imagehash; extra == "type_image_path"->visions[type_image_path]==0.4.4->pandas_profiling) (1.14.0)
Requirement already satisfied: setuptools in c:\forpit2\lib\site-packages (from kiwisolver>=1.0.1->matplotlib>=3.2.0->pandas_profiling) (45.2.0.post20200210)
Requirement already satisfied: llvmlite<0.32.0,>=0.31.0dev0 in c:\forpit2\lib\site-packages (from numba>=0.38.1->phik>=0.9.10->pandas_profiling) (0.31.0)
Requirement already satisfied: notebook>=4.4.1 in c:\forpit2\lib\site-packages (from widgetsnbextension~=3.5.0->ipywidgets>=7.5.1->pandas_profiling) (6.0.3)
Requirement already satisfied: tornado>=4.2 in c:\forpit2\lib\site-packages (from ipykernel>=4.5.1->ipywidgets>=7.5.1->pandas_profiling) (6.0.3)
Requirement already satisfied: jupyter-client in c:\forpit2\lib\site-packages (from ipykernel>=4.5.1->ipywidgets>=7.5.1->pandas_profiling) (5.3.4)
Requirement already satisfied: colorama; sys_platform == "win32" in c:\forpit2\lib\site-packages (from ipython>=4.0.0; python_version >= "3.3"->ipywidgets>=7.5.1->pandas_profiling) (0.4.3)
Requirement already satisfied: pygments in c:\forpit2\lib\site-packages (from ipython>=4.0.0; python_version >= "3.3"->ipywidgets>=7.5.1->pandas_profiling) (2.5.2)
Requirement already satisfied: jedi>=0.10 in c:\forpit2\lib\site-packages (from ipython>=4.0.0; python_version >= "3.3"->ipywidgets>=7.5.1->pandas_profiling) (0.14.1)
Requirement already satisfied: backcall in c:\forpit2\lib\site-packages (from ipython>=4.0.0; python_version >= "3.3"->ipywidgets>=7.5.1->pandas_profiling) (0.1.0)
Requirement already satisfied: pickleshare in c:\forpit2\lib\site-packages (from ipython>=4.0.0; python_version >= "3.3"->ipywidgets>=7.5.1->pandas_profiling) (0.7.5)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in c:\forpit2\lib\site-packages (from ipython>=4.0.0; python_version >= "3.3"->ipywidgets>=7.5.1->pandas_profiling) (3.0.3)
Requirement already satisfied: ipython-genutils in c:\forpit2\lib\site-packages (from traitlets>=4.3.1->ipywidgets>=7.5.1->pandas_profiling) (0.2.0)
Requirement already satisfied: jsonschema!=2.5.0,>=2.4 in c:\forpit2\lib\site-packages (from nbformat>=4.2.0->ipywidgets>=7.5.1->pandas_profiling) (3.2.0)
Requirement already satisfied: jupyter-core in c:\forpit2\lib\site-packages (from nbformat>=4.2.0->ipywidgets>=7.5.1->pandas_profiling) (4.6.1)
Requirement already satisfied: Send2Trash in c:\forpit2\lib\site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.5.1->pandas_profiling) (1.5.0)
Requirement already satisfied: pyzmq>=17 in c:\forpit2\lib\site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.5.1->pandas_profiling) (18.1.1)
Requirement already satisfied: prometheus-client in c:\forpit2\lib\site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.5.1->pandas_profiling) (0.7.1)
Requirement already satisfied: nbconvert in c:\forpit2\lib\site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.5.1->pandas_profiling) (5.6.1)
Requirement already satisfied: terminado>=0.8.1 in c:\forpit2\lib\site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.5.1->pandas_profiling) (0.8.3)
Requirement already satisfied: pywin32>=1.0; sys_platform == "win32" in c:\forpit2\lib\site-packages (from jupyter-client->ipykernel>=4.5.1->ipywidgets>=7.5.1->pandas_profiling) (227)
Requirement already satisfied: parso>=0.5.0 in c:\forpit2\lib\site-packages (from jedi>=0.10->ipython>=4.0.0; python_version >= "3.3"->ipywidgets>=7.5.1->pandas_profiling) (0.5.2)
Requirement already satisfied: wcwidth in c:\forpit2\lib\site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=4.0.0; python_version >= "3.3"->ipywidgets>=7.5.1->pandas_profiling) (0.1.8)
Requirement already satisfied: importlib-metadata; python_version < "3.8" in c:\forpit2\lib\site-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2.0->ipywidgets>=7.5.1->pandas_profiling) (1.5.0)
Requirement already satisfied: pyrsistent>=0.14.0 in c:\forpit2\lib\site-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2.0->ipywidgets>=7.5.1->pandas_profiling) (0.15.7)
Requirement already satisfied: testpath in c:\forpit2\lib\site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.5.1->pandas_profiling) (0.4.4)
Requirement already satisfied: entrypoints>=0.2.2 in c:\forpit2\lib\site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.5.1->pandas_profiling) (0.3)
Requirement already satisfied: bleach in c:\forpit2\lib\site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.5.1->pandas_profiling) (3.1.0)
Requirement already satisfied: pandocfilters>=1.4.1 in c:\forpit2\lib\site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.5.1->pandas_profiling) (1.4.2)
Requirement already satisfied: mistune<2,>=0.8.1 in c:\forpit2\lib\site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.5.1->pandas_profiling) (0.8.4)
Requirement already satisfied: defusedxml in c:\forpit2\lib\site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.5.1->pandas_profiling) (0.6.0)
Requirement already satisfied: zipp>=0.5 in c:\forpit2\lib\site-packages (from importlib-metadata; python_version < "3.8"->jsonschema!=2.5.0,>=2.4->nbformat>=4.2.0->ipywidgets>=7.5.1->pandas_profiling) (2.2.0)
Requirement already satisfied: webencodings in c:\forpit2\lib\site-packages (from bleach->nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.5.1->pandas_profiling) (0.5.1)
Installing collected packages: tangled-up-in-unicode, pandas, imagehash, visions, certifi, matplotlib, tqdm, missingno, phik, requests, pandas-profiling
  Attempting uninstall: pandas
    Found existing installation: pandas 1.0.1
    Uninstalling pandas-1.0.1:
      Successfully uninstalled pandas-1.0.1

ERROR: Could not install packages due to an EnvironmentError: [WinError 5] Отказано в доступе: 'c:\\forpit2\\lib\\site-packages\\~andas\\_libs\\algos.cp37-win_amd64.pyd'
Consider using the `--user` option or check the permissions.

In [2]:
data = pd.read_csv('taxi.csv') #для начала оценим обставку...
data.head()

,offer_gk,weekday_key,hour_key,driver_gk,order_gk,driver_latitude,driver_longitude,origin_order_latitude,origin_order_longitude,distance_km,duration_min,offer_class_group,ride_type_desc,driver_response
0,1105373,5,20,6080,174182,55.818842,37.334562,55.814567,37.355010,-1.000,-1.000,Economy,private,0
1,759733,5,14,6080,358774,55.805342,37.515023,55.819329,37.466398,18.802,25.217,Standard,private,1
2,416977,6,14,6080,866260,55.813978,37.347688,55.814827,37.354074,6.747,9.800,Economy,private,0
3,889660,2,6,6080,163522,55.745922,37.421748,55.743469,37.431130,-1.000,-1.000,Economy,private,1
4,1120055,4,16,6080,506710,55.803578,37.521602,55.812559,37.527407,12.383,19.250,Economy,private,1

при первом просмотре датасета по колонкам, сразу просится найти расстояние от водителя до пассажира, думаю этот параметр нам может пригодиться

In [3]:
point_latitude = data['driver_latitude'] - data['origin_order_latitude']
point_longitude = data['driver_longitude'] - data['origin_order_longitude']

In [4]:
data['distance_driver_passanger_LAT'] = point_latitude
data['distance_driver_passanger_LONG'] = point_longitude

In [5]:
data.head()

,offer_gk,weekday_key,hour_key,driver_gk,order_gk,driver_latitude,driver_longitude,origin_order_latitude,origin_order_longitude,distance_km,duration_min,offer_class_group,ride_type_desc,driver_response,distance_driver_passanger_LAT,distance_driver_passanger_LONG
0,1105373,5,20,6080,174182,55.818842,37.334562,55.814567,37.355010,-1.000,-1.000,Economy,private,0,0.004275,-0.020448
1,759733,5,14,6080,358774,55.805342,37.515023,55.819329,37.466398,18.802,25.217,Standard,private,1,-0.013987,0.048625
2,416977,6,14,6080,866260,55.813978,37.347688,55.814827,37.354074,6.747,9.800,Economy,private,0,-0.000849,-0.006386
3,889660,2,6,6080,163522,55.745922,37.421748,55.743469,37.431130,-1.000,-1.000,Economy,private,1,0.002453,-0.009382
4,1120055,4,16,6080,506710,55.803578,37.521602,55.812559,37.527407,12.383,19.250,Economy,private,1,-0.008981,-0.005805

не уверена что верно поняла параметр ride_type_desc, но думаю это тот кто повезет нас (частное лицо, фирма ... и какие то еще 2 не знаю как перевести),  пока оставим их

In [6]:
data.ride_type_desc.value_counts()

private      91207
business      8533
affiliate      224
SMB             36
Name: ride_type_desc, dtype: int64

посомтрим на 'странные' данные через describe

In [7]:
data.describe()

,offer_gk,weekday_key,hour_key,driver_gk,order_gk,driver_latitude,driver_longitude,origin_order_latitude,origin_order_longitude,distance_km,duration_min,driver_response,distance_driver_passanger_LAT,distance_driver_passanger_LONG
count,1.000000e+05,100000.000000,100000.000000,100000.000000,100000.00000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000
mean,5.662189e+05,3.159860,13.827790,3446.376360,460867.01291,55.700824,37.492292,55.772440,37.541637,18.393518,23.134841,0.492480,-0.071616,-0.049345
std,3.259360e+05,2.054222,7.306496,2038.738677,266064.98953,2.135903,1.454640,0.665985,0.467758,41.129296,33.890105,0.499946,2.217162,1.520378
min,4.000000e+00,0.000000,0.000000,14.000000,18.00000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,0.000000,-57.311121,-39.132620
25%,2.855552e+05,1.000000,8.000000,1421.000000,229178.50000,55.708651,37.413497,55.708032,37.407117,-1.000000,-1.000000,0.000000,-0.003033,-0.005587
50%,5.656715e+05,3.000000,16.000000,3506.500000,462420.00000,55.772904,37.533664,55.772561,37.532537,10.411500,19.700000,0.000000,-0.000001,0.000054
75%,8.487198e+05,5.000000,20.000000,5242.000000,690894.00000,55.960667,37.624113,55.962000,37.624358,30.665250,37.867000,1.000000,0.004318,0.006700
max,1.130355e+06,6.000000,23.000000,6806.000000,920344.00000,56.174097,38.280547,56.311121,38.243608,5234.283000,3958.283000,1.000000,56.984804,38.850971

из подозрительного можно отметить дистанцию в км, если это расстояние которое нужно проехать думаю оно не может быть отрицателным, а если это расстояние от водилы до чела, то тоже можно сделать аналогичные выводы, но смысловую нагрузку нести разную, хотя.. посмотрим дальше и не ьудем делать поспешные выводы

так же duration_min и distance_km , данном параметре странный максимум и минимум

а так же значени -1, скорее всего были отсутсвовал данные, думаю это выбросы, нужно подумать что делать с ними

пропусков нет, а так же видим 2 категориальных признака

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 16 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   offer_gk                        100000 non-null  int64
 1   weekday_key                     100000 non-null  int64
 2   hour_key                        100000 non-null  int64
 3   driver_gk                       100000 non-null  int64
 4   order_gk                        100000 non-null  int64
 5   driver_latitude                 100000 non-null  float64
 6   driver_longitude                100000 non-null  float64
 7   origin_order_latitude           100000 non-null  float64
 8   origin_order_longitude          100000 non-null  float64
 9   distance_km                     100000 non-null  float64
 10  duration_min                    100000 non-null  float64
 11  offer_class_group               100000 non-null  object
 12  ride_type_desc                  100000 non-null  object
 13  driver_response                 100000 non-null  int64
 14  distance_driver_passanger_LAT   100000 non-null  float64
 15  distance_driver_passanger_LONG  100000 non-null  float64
dtypes: float64(8), int64(6), object(2)
memory usage: 12.2+ MB

In [9]:
data.corr()>0.97

,offer_gk,weekday_key,hour_key,driver_gk,order_gk,driver_latitude,driver_longitude,origin_order_latitude,origin_order_longitude,distance_km,duration_min,driver_response,distance_driver_passanger_LAT,distance_driver_passanger_LONG
offer_gk,True,False,False,False,False,False,False,False,False,False,False,False,False,False
weekday_key,False,True,False,False,False,False,False,False,False,False,False,False,False,False
hour_key,False,False,True,False,False,False,False,False,False,False,False,False,False,False
driver_gk,False,False,False,True,False,False,False,False,False,False,False,False,False,False
order_gk,False,False,False,False,True,False,False,False,False,False,False,False,False,False
driver_latitude,False,False,False,False,False,True,True,False,False,False,False,False,False,False
driver_longitude,False,False,False,False,False,True,True,False,False,False,False,False,False,False
origin_order_latitude,False,False,False,False,False,False,False,True,False,False,False,False,False,False
origin_order_longitude,False,False,False,False,False,False,False,False,True,False,False,False,False,False
distance_km,False,False,False,False,False,False,False,False,False,True,True,False,False,False
duration_min,False,False,False,False,False,False,False,False,False,True,True,False,False,False
driver_response,False,False,False,False,False,False,False,False,False,False,False,True,False,False
distance_driver_passanger_LAT,False,False,False,False,False,False,False,False,False,False,False,False,True,True
distance_driver_passanger_LONG,False,False,False,False,False,False,False,False,False,False,False,False,True,True

In [10]:
data.drop_duplicates().shape

(100000, 16)

In [11]:
data['offer_class_group'].unique()

array(['Economy', 'Standard', 'XL', 'Kids', 'Delivery', 'Test', 'Premium',
       'VIP', 'VIP+'], dtype=object)

In [12]:
data = data[data['offer_class_group']!='Test'] #значение -1,0 можно удалить эти значению их очень мало

In [13]:
data.head()

,offer_gk,weekday_key,hour_key,driver_gk,order_gk,driver_latitude,driver_longitude,origin_order_latitude,origin_order_longitude,distance_km,duration_min,offer_class_group,ride_type_desc,driver_response,distance_driver_passanger_LAT,distance_driver_passanger_LONG
0,1105373,5,20,6080,174182,55.818842,37.334562,55.814567,37.355010,-1.000,-1.000,Economy,private,0,0.004275,-0.020448
1,759733,5,14,6080,358774,55.805342,37.515023,55.819329,37.466398,18.802,25.217,Standard,private,1,-0.013987,0.048625
2,416977,6,14,6080,866260,55.813978,37.347688,55.814827,37.354074,6.747,9.800,Economy,private,0,-0.000849,-0.006386
3,889660,2,6,6080,163522,55.745922,37.421748,55.743469,37.431130,-1.000,-1.000,Economy,private,1,0.002453,-0.009382
4,1120055,4,16,6080,506710,55.803578,37.521602,55.812559,37.527407,12.383,19.250,Economy,private,1,-0.008981,-0.005805

In [14]:
data.shape

(99992, 16)

In [15]:
data[data.loc[:, :]==-1].count()

offer_gk                              0
weekday_key                           0
hour_key                              0
driver_gk                             0
order_gk                              0
driver_latitude                     140
driver_longitude                    140
origin_order_latitude                13
origin_order_longitude               13
distance_km                       26199
duration_min                      26199
offer_class_group                     0
ride_type_desc                        0
driver_response                       0
distance_driver_passanger_LAT         0
distance_driver_passanger_LONG        0
dtype: int64

In [16]:
data[data['distance_km']<=1200].describe()

,offer_gk,weekday_key,hour_key,driver_gk,order_gk,driver_latitude,driver_longitude,origin_order_latitude,origin_order_longitude,distance_km,duration_min,driver_response,distance_driver_passanger_LAT,distance_driver_passanger_LONG
count,9.997600e+04,99976.000000,99976.000000,99976.000000,99976.000000,99976.000000,99976.000000,99976.000000,99976.000000,99976.000000,99976.000000,99976.000000,99976.000000,99976.000000
mean,5.662166e+05,3.159858,13.827279,3446.435214,460873.710781,55.700803,37.492275,55.772436,37.541630,18.033574,22.870949,0.492408,-0.071633,-0.049354
std,3.259319e+05,2.054280,7.306708,2038.687805,266072.376527,2.136159,1.454813,0.666064,0.467812,23.937258,22.926970,0.499945,2.217428,1.520561
min,4.000000e+00,0.000000,0.000000,14.000000,18.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,0.000000,-57.311121,-39.132620
25%,2.855608e+05,1.000000,8.000000,1421.000000,229182.500000,55.708610,37.413497,55.707996,37.407117,-1.000000,-1.000000,0.000000,-0.003033,-0.005586
50%,5.656715e+05,3.000000,16.000000,3507.000000,462420.000000,55.772904,37.533643,55.772561,37.532528,10.410500,19.700000,0.000000,-0.000001,0.000055
75%,8.486940e+05,5.000000,20.000000,5242.000000,690894.000000,55.960673,37.624102,55.962006,37.624354,30.639500,37.867000,1.000000,0.004318,0.006700
max,1.130355e+06,6.000000,23.000000,6806.000000,920344.000000,56.174097,38.280547,56.311121,38.243608,1058.824000,871.000000,1.000000,56.984804,38.850971

In [17]:
data = data[data['distance_km']<=1200]

In [18]:
data[data['distance_km']<1]

,offer_gk,weekday_key,hour_key,driver_gk,order_gk,driver_latitude,driver_longitude,origin_order_latitude,origin_order_longitude,distance_km,duration_min,offer_class_group,ride_type_desc,driver_response,distance_driver_passanger_LAT,distance_driver_passanger_LONG
0,1105373,5,20,6080,174182,55.818842,37.334562,55.814567,37.355010,-1.0,-1.0,Economy,private,0,0.004275,-0.020448
3,889660,2,6,6080,163522,55.745922,37.421748,55.743469,37.431130,-1.0,-1.0,Economy,private,1,0.002453,-0.009382
6,103326,2,11,6080,615584,55.753508,37.663742,55.757251,37.659064,-1.0,-1.0,Standard,business,1,-0.003743,0.004678
19,533917,5,8,6080,596531,55.913718,37.401395,55.921554,37.403505,-1.0,-1.0,Standard,business,0,-0.007836,-0.002110
21,123897,4,12,6080,185909,55.766763,37.607275,55.772388,37.606330,-1.0,-1.0,Standard,business,0,-0.005625,0.000945
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99981,397745,1,23,2442,383092,55.961397,37.413560,55.962322,37.407117,-1.0,-1.0,Standard,private,0,-0.000925,0.006443
99987,871592,4,23,2442,802677,55.961121,37.414019,55.961995,37.406355,-1.0,-1.0,Standard,private,0,-0.000874,0.007664
99991,619039,6,23,2442,323136,55.961239,37.413497,55.962322,37.407117,-1.0,-1.0,Standard,private,0,-0.001083,0.006380
99992,1021230,1,1,2442,351741,55.961301,37.413497,55.966694,37.415754,0.0,0.0,Standard,private,0,-0.005393,-0.002257
99994,915788,5,0,2442,636975,55.961351,37.413864,55.964220,37.423526,-1.0,-1.0,Economy,private,0,-0.002869,-0.009662

In [19]:
data.shape

(99976, 16)

In [20]:
data = data.drop(['offer_gk', 'order_gk', 'driver_gk'], axis=1)
data.head()

,weekday_key,hour_key,driver_latitude,driver_longitude,origin_order_latitude,origin_order_longitude,distance_km,duration_min,offer_class_group,ride_type_desc,driver_response,distance_driver_passanger_LAT,distance_driver_passanger_LONG
0,5,20,55.818842,37.334562,55.814567,37.355010,-1.000,-1.000,Economy,private,0,0.004275,-0.020448
1,5,14,55.805342,37.515023,55.819329,37.466398,18.802,25.217,Standard,private,1,-0.013987,0.048625
2,6,14,55.813978,37.347688,55.814827,37.354074,6.747,9.800,Economy,private,0,-0.000849,-0.006386
3,2,6,55.745922,37.421748,55.743469,37.431130,-1.000,-1.000,Economy,private,1,0.002453,-0.009382
4,4,16,55.803578,37.521602,55.812559,37.527407,12.383,19.250,Economy,private,1,-0.008981,-0.005805

как мы заметили ранее distance_km и duration_min высокая корреляция - 0.96, соответственно нам не нужны оба этих признака для построения модели, так как они оба содержат одинаковую информацию, удалим признак duration_min из датасета.

In [21]:
data = data.drop(['duration_min'], axis=1)
data.head()

,weekday_key,hour_key,driver_latitude,driver_longitude,origin_order_latitude,origin_order_longitude,distance_km,offer_class_group,ride_type_desc,driver_response,distance_driver_passanger_LAT,distance_driver_passanger_LONG
0,5,20,55.818842,37.334562,55.814567,37.355010,-1.000,Economy,private,0,0.004275,-0.020448
1,5,14,55.805342,37.515023,55.819329,37.466398,18.802,Standard,private,1,-0.013987,0.048625
2,6,14,55.813978,37.347688,55.814827,37.354074,6.747,Economy,private,0,-0.000849,-0.006386
3,2,6,55.745922,37.421748,55.743469,37.431130,-1.000,Economy,private,1,0.002453,-0.009382
4,4,16,55.803578,37.521602,55.812559,37.527407,12.383,Economy,private,1,-0.008981,-0.005805

In [22]:
data.drop(['driver_latitude', 'driver_longitude', 'origin_order_latitude', 'origin_order_longitude'], axis =1, inplace = True)

In [23]:

from sklearn.preprocessing import LabelEncoder, OneHotEncoder

label_enc = LabelEncoder()
oh_enc = OneHotEncoder()

In [24]:
ohe_class = oh_enc.fit_transform(data[['offer_class_group']]).toarray()
ohe_class = pd.DataFrame(ohe_class, columns=oh_enc.categories_[0])
ohe_class

       Delivery  Economy  Kids  Premium  Standard  VIP  VIP+   XL
0           0.0      1.0   0.0      0.0       0.0  0.0   0.0  0.0
1           0.0      0.0   0.0      0.0       1.0  0.0   0.0  0.0
2           0.0      1.0   0.0      0.0       0.0  0.0   0.0  0.0
3           0.0      1.0   0.0      0.0       0.0  0.0   0.0  0.0
4           0.0      1.0   0.0      0.0       0.0  0.0   0.0  0.0
...         ...      ...   ...      ...       ...  ...   ...  ...
99971       0.0      1.0   0.0      0.0       0.0  0.0   0.0  0.0
99972       0.0      1.0   0.0      0.0       0.0  0.0   0.0  0.0
99973       0.0      0.0   0.0      0.0       1.0  0.0   0.0  0.0
99974       0.0      1.0   0.0      0.0       0.0  0.0   0.0  0.0
99975       0.0      0.0   0.0      0.0       1.0  0.0   0.0  0.0

[99976 rows x 8 columns]

In [25]:
ohe_ride = oh_enc.fit_transform(data[['ride_type_desc']]).toarray()
ohe_ride = pd.DataFrame(ohe_ride, columns=oh_enc.categories_[0])
ohe_ride

       SMB  affiliate  business  private
0      0.0        0.0       0.0      1.0
1      0.0        0.0       0.0      1.0
2      0.0        0.0       0.0      1.0
3      0.0        0.0       0.0      1.0
4      0.0        0.0       0.0      1.0
...    ...        ...       ...      ...
99971  0.0        0.0       0.0      1.0
99972  0.0        0.0       0.0      1.0
99973  0.0        0.0       0.0      1.0
99974  0.0        0.0       0.0      1.0
99975  0.0        0.0       0.0      1.0

[99976 rows x 4 columns]

In [26]:
data = data.reset_index()

In [27]:
data = data.join(ohe_class, how = 'left')

In [28]:
data

,index,weekday_key,hour_key,distance_km,offer_class_group,ride_type_desc,driver_response,distance_driver_passanger_LAT,distance_driver_passanger_LONG,Delivery,Economy,Kids,Premium,Standard,VIP,VIP+,XL
0,0,5,20,-1.000,Economy,private,0,0.004275,-0.020448,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1,5,14,18.802,Standard,private,1,-0.013987,0.048625,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2,2,6,14,6.747,Economy,private,0,-0.000849,-0.006386,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
3,3,2,6,-1.000,Economy,private,1,0.002453,-0.009382,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
4,4,4,16,12.383,Economy,private,1,-0.008981,-0.005805,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99971,99995,0,2,17.378,Economy,private,0,-0.005448,-0.002257,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
99972,99996,0,1,7.751,Economy,private,0,-0.003646,-0.000046,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
99973,99997,1,20,46.983,Standard,private,0,-0.000888,-0.002876,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
99974,99998,6,21,50.029,Economy,private,0,-0.003538,0.000321,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
99975,99999,0,23,54.811,Standard,private,0,-0.000958,0.006747,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0

In [29]:
data = data.join(ohe_ride)

In [30]:
data.drop(['offer_class_group', 'ride_type_desc'], axis=1, inplace=True)

In [31]:
headers = list(data.columns.values)

In [32]:
data.head()

,index,weekday_key,hour_key,distance_km,driver_response,distance_driver_passanger_LAT,distance_driver_passanger_LONG,Delivery,Economy,Kids,Premium,Standard,VIP,VIP+,XL,SMB,affiliate,business,private
0,0,5,20,-1.000,0,0.004275,-0.020448,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,1,5,14,18.802,1,-0.013987,0.048625,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,2,6,14,6.747,0,-0.000849,-0.006386,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,3,2,6,-1.000,1,0.002453,-0.009382,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,4,4,16,12.383,1,-0.008981,-0.005805,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [33]:
from sklearn import preprocessing

from sklearn.preprocessing import MinMaxScaler, StandardScaler

min_max_scaler = preprocessing.MinMaxScaler(feature_range=(0,1))

np_scaled = min_max_scaler.fit_transform(data)
data_norm = pd.DataFrame(np_scaled)
data_norm.columns = headers 
data_norm

,index,weekday_key,hour_key,distance_km,driver_response,distance_driver_passanger_LAT,distance_driver_passanger_LONG,Delivery,Economy,Kids,Premium,Standard,VIP,VIP+,XL,SMB,affiliate,business,private
0,0.00000,0.833333,0.869565,0.000000,0.0,0.501465,0.501544,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,0.00001,0.833333,0.608696,0.018684,1.0,0.501305,0.502429,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,0.00002,1.000000,0.608696,0.007310,0.0,0.501420,0.501724,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,0.00003,0.333333,0.260870,0.000000,1.0,0.501449,0.501686,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,0.00004,0.666667,0.695652,0.012628,1.0,0.501349,0.501731,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99971,0.99996,0.000000,0.086957,0.017341,0.0,0.501380,0.501777,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
99972,0.99997,0.000000,0.043478,0.008257,0.0,0.501396,0.501805,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
99973,0.99998,0.166667,0.869565,0.045274,0.0,0.501420,0.501769,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
99974,0.99999,1.000000,0.913043,0.048149,0.0,0.501397,0.501810,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
99975,1.00000,0.000000,1.000000,0.052661,0.0,0.501419,0.501892,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [34]:
data_norm.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99976 entries, 0 to 99975
Data columns (total 19 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   index                           99976 non-null  float64
 1   weekday_key                     99976 non-null  float64
 2   hour_key                        99976 non-null  float64
 3   distance_km                     99976 non-null  float64
 4   driver_response                 99976 non-null  float64
 5   distance_driver_passanger_LAT   99976 non-null  float64
 6   distance_driver_passanger_LONG  99976 non-null  float64
 7   Delivery                        99976 non-null  float64
 8   Economy                         99976 non-null  float64
 9   Kids                            99976 non-null  float64
 10  Premium                         99976 non-null  float64
 11  Standard                        99976 non-null  float64
 12  VIP                             99976 non-null  float64
 13  VIP+                            99976 non-null  float64
 14  XL                              99976 non-null  float64
 15  SMB                             99976 non-null  float64
 16  affiliate                       99976 non-null  float64
 17  business                        99976 non-null  float64
 18  private                         99976 non-null  float64
dtypes: float64(19)
memory usage: 14.5 MB

In [35]:
output_y = data_norm['driver_response']
input_x = data_norm[['weekday_key', 'hour_key', 'distance_driver_passanger_LAT', 'distance_driver_passanger_LONG', 'distance_km', 'Delivery', 'Economy', 'Kids', 'Premium', 'Standard', 'VIP', 'VIP+', 'XL', 'SMB', 'affiliate', 'business', 'private']]

In [36]:
from sklearn.model_selection import train_test_split

rand_state = 1000

X_train, X_test, y_train, y_test = train_test_split(input_x, output_y, test_size=0.25, random_state=rand_state)

In [283]:
data

In [37]:

from sklearn.ensemble import RandomForestClassifier
# выбираем 100 деревьев в качестве параметра
model=RandomForestClassifier(n_estimators=100)
# обучаем модель
model.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [47]:
!pip install matplotlib

Collecting matplotlib
  Using cached matplotlib-3.3.1-1-cp37-cp37m-win_amd64.whl (8.9 MB)
Requirement already satisfied: cycler>=0.10 in c:\forpit2\lib\site-packages (from matplotlib) (0.10.0)
Requirement already satisfied: numpy>=1.15 in c:\forpit2\lib\site-packages (from matplotlib) (1.18.1)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 in c:\forpit2\lib\site-packages (from matplotlib) (2.4.6)
Requirement already satisfied: certifi>=2020.06.20 in c:\forpit2\lib\site-packages (from matplotlib) (2020.6.20)
Requirement already satisfied: python-dateutil>=2.1 in c:\forpit2\lib\site-packages (from matplotlib) (2.8.1)
Requirement already satisfied: pillow>=6.2.0 in c:\forpit2\lib\site-packages (from matplotlib) (7.0.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\forpit2\lib\site-packages (from matplotlib) (1.1.0)
Requirement already satisfied: six in c:\forpit2\lib\site-packages (from cycler>=0.10->matplotlib) (1.14.0)
Requirement already satisfied: setuptools in c:\forpit2\lib\site-packages (from kiwisolver>=1.0.1->matplotlib) (45.2.0.post20200210)
Installing collected packages: matplotlib

ERROR: Could not install packages due to an EnvironmentError: [WinError 5] Отказано в доступе: 'C:\\FORPIT2\\Lib\\site-packages\\matplotlib\\ft2font.cp37-win_amd64.pyd'
Consider using the `--user` option or check the permissions.

In [45]:
import seaborn as sns
from matplotlib import pyplot as plt
from sklearn.ensemble import RandomForestClassifier

headers = list(X_train.columns.values)

feature_imp = pd.Series(model.feature_importances_,index=headers).sort_values(ascending=False)

f, ax = plt.subplots(figsize=(6, 6))
sns.barplot(x=feature_imp, y=feature_imp.index)

plt.xlabel('Важность атрибутов')
plt.ylabel('Атрибуты')
plt.title("Наиболее важные атрибуты")
plt.legend()
plt.show()

ValueError: variadic keyword parameters cannot have default values

In [82]:
feature_imp = pd.Series(model.feature_importances_,index=headers).sort_values(ascending=False)

f, ax = plt.subplots(figsize=(10, 10))
sns.barplot(x=feature_imp, y=feature_imp.index)

plt.xlabel('Важность атрибутов')
plt.ylabel('Атрибуты')
plt.title("Наиболее важные атрибуты")
plt.legend()
plt.show()

ValueError: Length of passed values is 17, index implies 19.

In [46]:

from sklearn.metrics import classification_report
model_pred = model.predict(X_test)

print(classification_report(y_test, model_pred))

model.score(X_test, y_test)

              precision    recall  f1-score   support

         0.0       0.75      0.69      0.72     12772
         1.0       0.70      0.76      0.73     12222

    accuracy                           0.72     24994
   macro avg       0.73      0.72      0.72     24994
weighted avg       0.73      0.72      0.72     24994

0.7239737537008882


Точность модели составляет 72%
думаю это не плохой результат